steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: $(system.defaultWorkingDirectory)/IdentityService/gradlew
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'